### PR TITLE
fix style #157

### LINKED ISSUE #157: Bug:list items style in footer

### PR DESCRIPTION
**Pull request by amanshawar**
make login page work if there is no upload photo BUG
make style the footer in item list work BUG fix #157

### CODE REVIEW

File: client/src/components/ItemList/index.js [hunk 1]
```diff
@@ -12,8 +12,14 @@ import {
   GButtonContainer,
   StyledBottom,
   StyledLink,
+<<<<<<< HEAD
```
Comment (jema28) [inline client/src/components/ItemList/index.js]: There's a merge conflict here.

**Review by jema28 — CHANGES_REQUESTED** [review]

**Review by jema28 — APPROVED** [review]
