### PR TITLE
Fix bug

### LINKED ISSUE #192: BUG: fix the extension  of image to select

### PR DESCRIPTION
**Pull request by amanshawar**
appear the images in upload photo fix #192 
fix the moves when the user logged in or not #186 
fix the crash of server if there is no user #191

### CODE REVIEW

File: server/controllers/getItems.js [hunk 1]
```diff
@@ -17,26 +17,27 @@ exports.getItems = (req, res) => {
...
+                brand: record.get('Brand Names')[0],
+                condition: record.get('Condition'),
+                age: record.get('Age'),
+                details: record.get('Details'),
+                brandId: record.get('Brand')[0],
+                colors: record.get('Colours'),
+                hex: record.get('Colour Hex Code'),
+                colorshex: record.get('Colours Hex Codes'),
+                sizeCategory: record.get('Size Category'),
+              });
```
Comment (orjwan98) [inline server/controllers/getItems.js:41]: You seem to have removed `pattern`. Is there any reason as to why?

File: client/src/components/Upload/index.js [hunk 2]
```diff
@@ -47,6 +47,7 @@ class Upload extends Component {
               label="upload file"
               type="file"
               onChange={this.handleUploadFile}
+              accept="image/*"
```
Comment (orjwan98) [inline client/src/components/Upload/index.js:50]: What does `accept="image/*"` do?

**Review by orjwan98 — APPROVED** [review]

**Review by Hadeel-Salamin — APPROVED** [review]

**Review by jema28 — APPROVED** [review]
